
// Define regions for postal codes
export const postalCodeRegions = [
  { prefix: "01", region: "PAIS_VASCO" },
  { prefix: "02", region: "CASTILLA_MANCHA" },
  { prefix: "03", region: "VALENCIA" },
  { prefix: "04", region: "ANDALUCIA" },
  { prefix: "05", region: "CASTILLA_LEON" },
  { prefix: "06", region: "EXTREMADURA" },
  { prefix: "07", region: "BALEARES" },
  { prefix: "08", region: "CATALUNYA" },
  { prefix: "09", region: "CASTILLA_LEON" },
  { prefix: "10", region: "EXTREMADURA" },
  { prefix: "11", region: "ANDALUCIA" },
  { prefix: "12", region: "VALENCIA" },
  { prefix: "13", region: "CASTILLA_MANCHA" },
  { prefix: "14", region: "ANDALUCIA" },
  { prefix: "15", region: "GALICIA" },
  { prefix: "16", region: "CASTILLA_MANCHA" },
  { prefix: "17", region: "CATALUNYA" },
  { prefix: "18", region: "ANDALUCIA" },
  { prefix: "19", region: "CASTILLA_MANCHA" },
  { prefix: "20", region: "PAIS_VASCO" },
  { prefix: "21", region: "ANDALUCIA" },
  { prefix: "22", region: "ARAGON" },
  { prefix: "23", region: "ANDALUCIA" },
  { prefix: "24", region: "CASTILLA_LEON" },
  { prefix: "25", region: "CATALUNYA" },
  { prefix: "26", region: "LA_RIOJA" },
  { prefix: "27", region: "GALICIA" },
  { prefix: "28", region: "MADRID" },
  { prefix: "29", region: "ANDALUCIA" },
  { prefix: "30", region: "MURCIA" },
  { prefix: "31", region: "NAVARRA" },
  { prefix: "32", region: "GALICIA" },
  { prefix: "33", region: "ASTURIAS" },
  { prefix: "34", region: "CASTILLA_LEON" },
  { prefix: "35", region: "CANARIAS" },
  { prefix: "36", region: "GALICIA" },
  { prefix: "37", region: "CASTILLA_LEON" },
  { prefix: "38", region: "CANARIAS" },
  { prefix: "39", region: "CANTABRIA" },
  { prefix: "40", region: "CASTILLA_LEON" },
  { prefix: "41", region: "ANDALUCIA" },
  { prefix: "42", region: "CASTILLA_LEON" },
  { prefix: "43", region: "CATALUNYA" },
  { prefix: "44", region: "ARAGON" },
  { prefix: "45", region: "CASTILLA_MANCHA" },
  { prefix: "46", region: "VALENCIA" },
  { prefix: "47", region: "CASTILLA_LEON" },
  { prefix: "48", region: "PAIS_VASCO" },
  { prefix: "49", region: "CASTILLA_LEON" },
  { prefix: "50", region: "ARAGON" },
  { prefix: "51", region: "CEUTA" },
  { prefix: "52", region: "MELILLA" },
];

export const comunidadesAutonomas = [
  { id: "ANDALUCIA", nombre: "ANDALUCÍA", normativa: "Decreto-Ley 4/2023", aplicaSiempre: true },
  { id: "ARAGON", nombre: "ARAGÓN", normativa: "No aplica", aplicaSiempre: false },
  { id: "ASTURIAS", nombre: "ASTURIAS", normativa: "No aplica", aplicaSiempre: false },
  { id: "BALEARES", nombre: "ILLES BALEARS", normativa: "No aplica", aplicaSiempre: false },
  { id: "CANARIAS", nombre: "CANARIAS", normativa: "No aplica", aplicaSiempre: false },
  { id: "CANTABRIA", nombre: "CANTABRIA", normativa: "No aplica", aplicaSiempre: false },
  { id: "CASTILLA_LEON", nombre: "CASTILLA Y LEÓN", normativa: "Orden EEI/1036/2021", aplicaSiempre: false },
  { id: "CASTILLA_MANCHA", nombre: "CASTILLA-LA MANCHA", normativa: "No aplica", aplicaSiempre: false },
  { id: "CATALUNYA", nombre: "CATALUNYA", normativa: "Decret 192/2023", aplicaSiempre: true },
  { id: "VALENCIA", nombre: "COM. VALENCIANA", normativa: "No aplica", aplicaSiempre: false },
  { id: "EXTREMADURA", nombre: "EXTREMADURA", normativa: "No aplica", aplicaSiempre: false },
  { id: "GALICIA", nombre: "GALICIA", normativa: "No aplica", aplicaSiempre: false },
  { id: "MADRID", nombre: "MADRID", normativa: "No aplica", aplicaSiempre: false },
  { id: "MURCIA", nombre: "MURCIA", normativa: "No aplica", aplicaSiempre: false },
  { id: "NAVARRA", nombre: "NAVARRA", normativa: "No aplica", aplicaSiempre: false },
  { id: "PAIS_VASCO", nombre: "PAÍS VASCO-EUSKADI", normativa: "No aplica", aplicaSiempre: false },
  { id: "LA_RIOJA", nombre: "LA RIOJA", normativa: "No aplica", aplicaSiempre: false },
  { id: "CEUTA", nombre: "CEUTA", normativa: "No aplica", aplicaSiempre: false },
  { id: "MELILLA", nombre: "MELILLA", normativa: "No aplica", aplicaSiempre: false },
];

export const periodoInstalacion = [
  { id: "entre_1971_1977", nombre: "Entre 1971 y 1977", rsif: "Decreto 3214/1971" },
  { id: "entre_1978_2011", nombre: "Entre 1978 y 2011", rsif: "RD 3099/1977" },
  { id: "entre_2012_2019", nombre: "Entre 2012 y 2019", rsif: "RD 138/2011" },
  { id: "desde_2020", nombre: "A partir de 2020", rsif: "RD 552/2019" },
  { id: "nueva", nombre: "Nueva", rsif: "RD 552/2019" },
];
